# Generated by Django 4.1.5 on 2023-04-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
    ]
