# Generated by Django 4.1.5 on 2023-04-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='medium_id',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='class_id',
            new_name='school_class',
        ),
        migrations.RenameField(
            model_name='classsection',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sessionmanager',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='class_id',
            new_name='school_class',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='designation_id',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='class',
            name='ais_id',
        ),
        migrations.RemoveField(
            model_name='class',
            name='lms_id',
        ),
        migrations.RemoveField(
            model_name='medium',
            name='lms_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='ais_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lms_id',
        ),
    ]
