# Generated by Django 4.1.5 on 2023-04-13 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0003_class_created_by_section_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='section_id_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAdmin.section'),
        ),
    ]
