# Generated by Django 4.1.5 on 2023-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0003_rename_created_by_categories_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='is_synced',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
