# Generated by Django 4.1.5 on 2023-04-13 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAdmin', '0005_alter_class_created_by_alter_class_section_id_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section_id_id',
        ),
        migrations.AddField(
            model_name='class',
            name='section_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
