# Generated by Django 4.1.5 on 2023-04-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0005_section_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_synced',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
