# Generated by Django 4.1.5 on 2023-04-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0008_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_synced',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
