# Generated by Django 4.1.5 on 2023-04-13 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0008_class_section_id_delete_classsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='section_id',
        ),
        migrations.AddField(
            model_name='class',
            name='section_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myAdmin.section'),
        ),
    ]
