# Generated by Django 4.1.5 on 2023-04-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0009_categories_is_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_synced',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
