# Generated by Django 4.1.5 on 2023-04-13 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0010_remove_class_section_id_classsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('adminbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myAdmin.adminbase')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=200)),
                ('parent_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'parent',
            },
            bases=('myAdmin.adminbase',),
        ),
    ]
