# Generated by Django 4.1.5 on 2023-04-13 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAdmin', '0011_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('adminbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myAdmin.adminbase')),
                ('admission_no', models.CharField(max_length=200)),
                ('roll_no', models.IntegerField(max_length=100)),
                ('academic_year', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('admission_data', models.DateField()),
                ('mobile', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAdmin.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAdmin.parent')),
                ('section_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAdmin.section')),
            ],
            options={
                'db_table': 'student',
            },
            bases=('myAdmin.adminbase',),
        ),
    ]
