# Generated by Django 4.1.5 on 2023-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0012_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='first_name',
            new_name='father_first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='last_name',
            new_name='mother_first_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent_type',
        ),
        migrations.AddField(
            model_name='parent',
            name='father_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='father_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mother_mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
