# Generated by Django 4.1.5 on 2023-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0013_rename_first_name_parent_father_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
    ]
