# Generated by Django 4.2.3 on 2024-02-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0015_otpdevice_delete_phonemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdevice',
            name='user',
        ),
    ]
