# Generated by Django 4.1.5 on 2023-04-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0017_department_designation_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIs',
            fields=[
                ('adminbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myAdmin.adminbase')),
                ('api_name', models.CharField(max_length=100)),
                ('api_url', models.CharField(max_length=500)),
                ('api_method', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'apis',
            },
            bases=('myAdmin.adminbase',),
        ),
    ]
