# Generated by Django 4.1.5 on 2023-04-16 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myAdmin', '0018_apis'),
    ]

    operations = [
        migrations.AddField(
            model_name='apis',
            name='base_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='apis',
            name='protocol',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apis',
            name='api_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apis',
            name='product_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('adminbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myAdmin.adminbase')),
                ('medium_name', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medium',
            },
            bases=('myAdmin.adminbase',),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('adminbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myAdmin.adminbase')),
                ('category_name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
            },
            bases=('myAdmin.adminbase',),
        ),
        migrations.AddField(
            model_name='class',
            name='medium_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myAdmin.medium'),
        ),
    ]
