from django.urls import path
from . import views
from . import otp

urlpatterns = [
    path('login', views.login_user, name='login_user'),
    path('logout', views.logout_user, name='logout_user'),
    path('signup', views.signup_user, name='signup_user'),
    path('add-address', views.add_address, name="add_address"),
    path('add-school', views.add_school, name="add_school"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('classes', views.classIndex, name="classIndex"),
    path('classes/delete/<int:id>', views.classDelete, name="classDelete"),
    path('classes/edit/<int:id>', views.classEdit, name="classEdit"),
    path('class/update', views.classUpdate, name="classUpdate"),
    path('class/sync/<int:id>', views.classSync, name="classSync"),
    path('medium', views.mediumIndex, name="mediumIndex"),
    path('medium/delete/<int:id>', views.mediumDelete, name="mediumDelete"),
    path('medium/edit/<int:id>', views.mediumEdit, name="mediumEdit"),
    path('medium/update', views.mediumUpdate, name="mediumUpdate"),
    path('medium/sync/<int:id>', views.mediumSync, name="mediumSync"),
    path('section', views.sectionIndex, name="sectionIndex"),
    path('section/delete/<int:id>', views.sectionDelete, name="sectionDelete"),
    path('section/edit/<int:id>', views.sectionEdit, name="sectionEdit"),
    path('section/update', views.sectionUpdate, name="sectionUpdate"),
    path('section/sync/<int:id>', views.sectionSync, name="sectionSync"),
    path('category', views.categoryIndex, name="categoryIndex"),
    path('category/delete/<int:id>', views.categoryDelete, name="categoryDelete"),
    path('category/edit/<int:id>', views.categoryEdit, name="categoryEdit"),
    path('category/update', views.categoryUpdate, name="categoryUpdate"),
    path('category/sync/<int:id>', views.categorySync, name="categorySync"),
    path('students', views.studentIndex, name="studentIndex"),
    path('student/delete/<int:id>', views.studentDelete, name="studentDelete"),
    path('student/edit/<int:id>', views.studentEdit, name="studentEdit"),
    path('student/update', views.studentUpdate, name="studentUpdate"),
    path('student/sync/<int:id>', views.studentSync, name="studentSync"),
    path('student/bulk-upload', views.studentBulkUpload, name="studentBulkUpload"),
    path('teachers', views.teacherIndex, name="teacherIndex"),
    path('teacher/delete/<int:id>', views.teacherDelete, name="teacherDelete"),
    path('teacher/edit/<int:id>', views.teacherEdit, name="teacherEdit"),
    path('teacher/update', views.teacherUpdate, name="teacherUpdate"),
    path('teacher/sync/<int:id>', views.teacherSync, name="teacherSync"),
    path('department', views.departmentIndex, name="departmentIndex"),
    path('department/delete/<int:id>', views.departmentDelete, name="departmentDelete"),
    path('department/edit/<int:id>', views.departmentEdit, name="departmentEdit"),
    path('department/update', views.departmentUpdate, name="departmentUpdate"),
    path('department/sync/<int:id>', views.departmentSync, name="departmentSync"),
    path('designation', views.designationIndex, name="designationIndex"),
    path('designation/delete/<int:id>', views.designationDelete, name="designationDelete"),
    path('designation/edit/<int:id>', views.designationEdit, name="designationEdit"),
    path('designation/update', views.designationUpdate, name="designationUpdate"),
    path('role', views.roleIndex, name="roleIndex"),
    path('role/delete/<int:id>', views.roleDelete, name="roleDelete"),
    path('role/edit/<int:id>', views.roleEdit, name="roleEdit"),
    path('role/update', views.roleUpdate, name="roleUpdate"),
    path('send-otp', otp.send_otp, name="send_otp")
]
